/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TictactoeRouteImport } from './routes/tictactoe'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ExperimentsIndexRouteImport } from './routes/experiments/index'
import { Route as ExperimentsIdRouteImport } from './routes/experiments/$id'

const TictactoeRoute = TictactoeRouteImport.update({
  id: '/tictactoe',
  path: '/tictactoe',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperimentsIndexRoute = ExperimentsIndexRouteImport.update({
  id: '/experiments/',
  path: '/experiments/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperimentsIdRoute = ExperimentsIdRouteImport.update({
  id: '/experiments/$id',
  path: '/experiments/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/tictactoe': typeof TictactoeRoute
  '/experiments/$id': typeof ExperimentsIdRoute
  '/experiments': typeof ExperimentsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/tictactoe': typeof TictactoeRoute
  '/experiments/$id': typeof ExperimentsIdRoute
  '/experiments': typeof ExperimentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/tictactoe': typeof TictactoeRoute
  '/experiments/$id': typeof ExperimentsIdRoute
  '/experiments/': typeof ExperimentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/tictactoe' | '/experiments/$id' | '/experiments'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/tictactoe' | '/experiments/$id' | '/experiments'
  id: '__root__' | '/' | '/tictactoe' | '/experiments/$id' | '/experiments/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TictactoeRoute: typeof TictactoeRoute
  ExperimentsIdRoute: typeof ExperimentsIdRoute
  ExperimentsIndexRoute: typeof ExperimentsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tictactoe': {
      id: '/tictactoe'
      path: '/tictactoe'
      fullPath: '/tictactoe'
      preLoaderRoute: typeof TictactoeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experiments/': {
      id: '/experiments/'
      path: '/experiments'
      fullPath: '/experiments'
      preLoaderRoute: typeof ExperimentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experiments/$id': {
      id: '/experiments/$id'
      path: '/experiments/$id'
      fullPath: '/experiments/$id'
      preLoaderRoute: typeof ExperimentsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TictactoeRoute: TictactoeRoute,
  ExperimentsIdRoute: ExperimentsIdRoute,
  ExperimentsIndexRoute: ExperimentsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
