/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TictactoeRouteImport } from './routes/tictactoe'
import { Route as ExperimentsRouteImport } from './routes/experiments'
import { Route as IndexRouteImport } from './routes/index'

const TictactoeRoute = TictactoeRouteImport.update({
  id: '/tictactoe',
  path: '/tictactoe',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperimentsRoute = ExperimentsRouteImport.update({
  id: '/experiments',
  path: '/experiments',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/experiments': typeof ExperimentsRoute
  '/tictactoe': typeof TictactoeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/experiments': typeof ExperimentsRoute
  '/tictactoe': typeof TictactoeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/experiments': typeof ExperimentsRoute
  '/tictactoe': typeof TictactoeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/experiments' | '/tictactoe'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/experiments' | '/tictactoe'
  id: '__root__' | '/' | '/experiments' | '/tictactoe'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExperimentsRoute: typeof ExperimentsRoute
  TictactoeRoute: typeof TictactoeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tictactoe': {
      id: '/tictactoe'
      path: '/tictactoe'
      fullPath: '/tictactoe'
      preLoaderRoute: typeof TictactoeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experiments': {
      id: '/experiments'
      path: '/experiments'
      fullPath: '/experiments'
      preLoaderRoute: typeof ExperimentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExperimentsRoute: ExperimentsRoute,
  TictactoeRoute: TictactoeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
